[project]
name = "dspy-commit"
version = "0.1.0"
description = "Generate a commit msg for staged files using dspy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dspy>=3.1.3",
]
